# Generated by Django 2.2.1 on 2019-05-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('properties', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccName', models.CharField(max_length=255)),
                ('ccNumber', models.CharField(max_length=16)),
                ('CVC', models.CharField(max_length=3)),
                ('expirationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Profile')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.CreditCard')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties')),
                ('realtyAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agents')),
            ],
        ),
    ]
