# Generated by Django 2.2.1 on 2019-05-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='CVC',
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='ccNumber',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expirationDate',
            field=models.CharField(default='01/25', max_length=5),
            preserve_default=False,
        ),
    ]
