# Generated by Django 2.2.1 on 2019-05-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='SSN',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='houseNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streetName',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
