# Generated by Django 2.2.1 on 2019-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_recentlyviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewed',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
