# Generated by Django 2.2.1 on 2019-05-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('room', models.IntegerField()),
                ('price', models.FloatField()),
                ('yearBuilt', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=999)),
                ('status', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agents')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(max_length=999)),
                ('houseNumber', models.FloatField()),
                ('zipCode', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden', models.BooleanField(blank=True)),
                ('garage', models.BooleanField(blank=True)),
                ('pets', models.BooleanField(blank=True)),
                ('accessibility', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=999)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertiesDetails'),
        ),
    ]
