# Generated by Django 2.2.1 on 2019-05-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(max_length=255)),
                ('houseNr', models.IntegerField(default=None)),
                ('zipCode', models.IntegerField(default=None)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden', models.BooleanField(default=None)),
                ('garage', models.BooleanField(default=None)),
                ('petAllowed', models.BooleanField(default=None)),
                ('Accessibility', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=255)),
                ('size', models.IntegerField(default=None)),
                ('room', models.IntegerField(default=None)),
                ('price', models.FloatField(default=None)),
                ('year_built', models.IntegerField(blank=True, default=None)),
                ('description', models.CharField(blank=True, default=None, max_length=999, null=True)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyAddress')),
                ('details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyDetails')),
            ],
        ),
    ]
