# Generated by Django 2.2.1 on 2019-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20190513_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='room',
            new_name='rooms',
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.IntegerField(),
        ),
    ]
